Library/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Library.ViewModels;
using Microsoft.AspNetCore.Authorization;
using AutoMapper;
using Library.Features.Admin;
using MediatR;

namespace Library.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly UserManager<User> _userManager;
        private IMediator _mediator;
        private IMapper _mapper;
        public AdminController(IMapper mapper, IMediator mediator, UserManager<User> userManager)
        {
            _mediator = mediator;
            _userManager = userManager;
            _mapper = mapper;
        }
        public IActionResult UsersList()
        {
            List<UsersListViewModel> userList = _mapper.Map<List<User>, List<UsersListViewModel>>(_userManager.Users.ToList());
            return View(userList);
        }
        [HttpGet]
        public IActionResult AddUser()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> AddUser(AddUserViewModel _model)
        {
            if (ModelState.IsValid)
            {
                var result = await _mediator.Send(new AddUser() { model = _model });
            }
            return RedirectToAction("UsersList");
        }
        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            User result = await _mediator.Send(new FindUserById() { Id = id });
            if (result == null)
            {
                return NotFound();
            }
            var model = await _mediator.Send(new EditUserGet() { user = result });
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> EditUser(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;
                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("UsersList");
                    }
                    else
                    {
                        foreach (var Error in result.Errors)
                        {
                            ModelState.AddModelError("", Error.Description);
                        }
                    }
                }
            }
            return View(model);
        }
        public async Task<IActionResult> DeleteUser(string id)
        {
            await _mediator.Send(new DeleteUser() { Id = id });
            return RedirectToAction("UsersList");
        }
        public string GeneratePassword()
        {
            Random rnd = new Random();
            string pass = "";
            string[] arr = {
                "A","a","B","b","C","c","D","d","E","e","F","f","T","t","1","2","3","4","5","6","7","8","9","0"
            };
            for (int i = 0; i < 10; i++)
            {
                pass = pass + arr[rnd.Next(0, 23)];
            }
            return pass;
        }
    }
}

Library/Controllers/BookController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Library.ViewModels;
using Microsoft.AspNetCore.Http;
using MediatR;
using Library.Features.BookFeatures.Queries;
using Library.Features.BookFeatures;

namespace Library.Controllers
{
    [Authorize(Roles = "librarian")]
    public class BookController : Controller
    {
        private IMediator _mediator;
        public BookController(IMediator mediator)
        {
            _mediator = mediator;
        }
        [HttpGet]
        public async Task<ActionResult> BookList(int? _AuthorId, int? _GenreId, int? _PublisherId, string _SearchString = null)
        {
            var result = await _mediator.Send(new LibrarianBooksList() { AuthorId = _AuthorId, GenreId = _GenreId, PublisherId = _PublisherId, SearchString = _SearchString });
            return View(result);
        }
        [HttpGet]
        public async Task<ActionResult> AddBookAsync()
        {
            return View(await _mediator.Send(new AddBook()));
        }
        [HttpPost]
        public async Task<ActionResult> AddBookAsync(AddBookViewModel _model, IFormFile _file)
        {
            if (ModelState.IsValid)
            {
                await _mediator.Send(new AddBookPost()
                {
                    file = _file,
                    model = _model
                });
            }
            return RedirectToAction("BookList");
        }
        public async Task<ActionResult> EditBookAsync(int id)
        {
            if (ModelState.IsValid)
            {
                var model = await _mediator.Send(new EditBook() { Id = id });
                return View(model);
            }
            else
            {
                return NotFound();
            }
        }
        [HttpPost]
        public async Task<ActionResult> EditBookAsync(AddBookViewModel _model)
        {
            if (ModelState.IsValid)
            {
                await _mediator.Send(new EditBookF() { model = _model });
                return RedirectToAction("BookList");
            }
            else
            {
                await _mediator.Send(new EditBookElseF() { model = _model });
                return View(_model);
            }
        }
        [HttpGet]
        public async Task<ActionResult> DeleteBook(int id)
        {
            var result = await _mediator.Send(new DeleteBookF() { Id = id });
            if (result != null)
            {
                return View(result);
            }
            else
            {
                return NotFound();
            }
        }
        [HttpPost, ActionName("DeleteBook")]
        public ActionResult DeleteBookConfirmed(int id)
        {
            _mediator.Send(new DeleteBookConfirmedF() { Id = id });
            return RedirectToAction("BookList");
        }
    }
}

Library/Controllers/GenreController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Library.Models;
using Library.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MediatR;
using Library.Features.GenreFeatures;

namespace Library.Controllers
{
    [Authorize(Roles = "librarian")]
    public class GenreController : Controller
    {
        private readonly IGenreRepository _genreRepository;
        private IMediator _mediator;
        public GenreController(IMediator mediator, IGenreRepository genreRepository)
        {
            _mediator = mediator;
            _genreRepository = genreRepository;
        }
        public async Task<ActionResult> GenreListAsync()
        {
            List<Genre> genres = await _genreRepository.GetLItem();
            return View(genres);
        }
        public ActionResult CreateGenre()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateGenre(Genre _genre)
        {
            if (ModelState.IsValid)
            {
                _mediator.Send(new AddGenre() { genre = _genre });
            }
            return RedirectToAction("GenreList");
        }
        [HttpGet]
        public async Task<ActionResult> EditGenreAsync(int id)
        {
            return View(await _mediator.Send(new EditGenreGet() { Id = id }));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditGenreAsync(Genre _genre)
        {
            if (ModelState.IsValid)
            {
                await _mediator.Send(new EditGenrePost() { genre = _genre });
            }
            return RedirectToAction("GenreList");
        }
        [HttpGet]
        public async Task<ActionResult> DeleteGenre(int id)
        {
            var GenreResult = await _mediator.Send(new DeleteGenreGetF() { Id = id });
            if (GenreResult == null)
            {
                return NotFound();
            }
            return View(GenreResult);
        }
        [HttpPost, ActionName("DeleteGenre")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteGenreConfirmed(int id)
        {
            _mediator.Send(new DeleteGenreConfirmedF() { Id = id });
            return RedirectToAction("GenreList");
        }
    }
}

Library/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Library.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Library.Features.RoleFeatures;
using MediatR;

namespace Library.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IMediator _mediator;

        public RolesController(UserManager<User> userManager, IMediator mediator)
        {
            _userManager = userManager;
            _mediator = mediator;
        }
        public async Task<IActionResult> RolesList()
        {
            var result = await _mediator.Send(new RoleListF());
            return View(result);
        }
        public IActionResult UsersList()
        {
            return View(_userManager.Users.ToList());
        }
        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateRole(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                var roleNameResult = _mediator.Send(new FindByNameRole() { Name = name });
                IdentityResult roleCreateResult = await _mediator.Send(new CreateRoleF() { Name = name });
                if (roleCreateResult.Succeeded)
                {
                    return RedirectToAction("RolesList");
                }
                else
                {
                    foreach (var e in roleCreateResult.Errors)
                    {
                        ModelState.AddModelError(string.Empty, e.Description);
                    }
                }
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> EditUserRole(string userId)
        {
            var EditResult = await _mediator.Send(new EditUserRoleGetF() { UserId = userId });
            if (EditResult.Id != null)
            {
                return View(EditResult);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> EditUserRole(string userId, List<string> roles)
        {
            var UserResult = await _mediator.Send(new EditUserRolePostF() { UserId = userId, Roles = roles });
            if (UserResult != null)
            {
                return RedirectToAction("UsersList", "Admin");
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> DeleteRole(string id)
        {
            await _mediator.Send(new DeleteRoleF() { Id = id });
            return RedirectToAction("RolesList");
        }
    }
}

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <title>@ViewData["Title"]-Библиотека</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Catalog" asp-action="BooksList">Библиотека</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Catalog" asp-action="BooksList">Каталог</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Reservation" asp-action="MyReservations">Мои книги</a>
                        </li>
                        @if (this.User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Admin" asp-action="UsersList">Работа с пользователями</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Roles" asp-action="RolesList">Список ролей</a>
                            </li>
                        }
                        @if (this.User.IsInRole("librarian"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-action="AuthorList" asp-controller="Author">Авторы</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-action="GenreList" asp-controller="Genre">Жанры</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-action="PublisherList" asp-controller="Publisher">Издатели</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="drop1" href="#" class="nav-link dropdown-toggle text-light" data-toggle="dropdown">
                                    Работа с книгами
                                    <span class="caret"></span>
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-action="BookList" asp-controller="Book">Список книг</a>
                                    <a class="dropdown-item" asp-action="ReservationList" asp-controller="Librarian">Забронированные книги</a>
                                    <a class="dropdown-item" asp-action="BookingList" asp-controller="Librarian">Выданные книги</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
            <partial name="_LoginPartial">
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>