Library/ViewModels/CatalogViewModel.cs
using Library.Models;
using System.Collections.Generic;

namespace Library.ViewModels
{
    public class CatalogViewModel
    {
        public BooksFilterViewModel BooksFilterViewModel { get; set; }
        public List<BookSelectViewModel> Books { get; set; }
        public PageViewModel PageViewModel { get; set; }      
        public User User { get; set; }
    }
}

Library/Controllers/CatalogController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Library.Models;
using Library.ViewModels;
using Microsoft.AspNetCore.Authorization;
using MediatR;
using Library.Features.BookFeatures.Queries;
using Library.Features.Admin;

namespace Library.Controllers
{
    public class CatalogController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IMediator _mediatr;
        public CatalogController(IMediator mediator, UserManager<User> userManager)
        {
            _userManager = userManager;
            _mediatr = mediator;
        }

        [HttpGet]
        public async Task<IActionResult> BooksList(int? AuthorId, int? PublisherId, int? GenreId, string SearchString = null)
        {
            User user;
            if (User.Identity.IsAuthenticated)
            {
                user = _userManager.GetUserAsync(HttpContext.User).Result;
            }
            else
            {
                user = null;
            }
            CatalogViewModel model = await _mediatr.Send(new BooksList()
            {
                page = 1,
                AuthorId = AuthorId,
                PublisherId = PublisherId,
                GenreId = GenreId,
                SearchString = SearchString,
                user = user
            }
            );
            return View(model);
        }
        [Authorize]
        public async Task<ActionResult> ReserveBookAsync(int bookId, string UserId)
        {
            if (UserId == null)
            {
                RedirectToAction("Login", "Account");
            }
            var bookResult = await _mediatr.Send(new FindByIdBook() { Id = bookId });
            var UserResult = _mediatr.Send(new FindUserById() { Id = UserId }).Result;
            if (!UserResult.EmailConfirmed)
            {
                RedirectToPage("ConfirmEmail");
            }
            var result = await _mediatr.Send(new ReserveBook() { Id = bookId, book = bookResult, user = UserResult });
            return View(result);
        }
        [Authorize]
        public async Task<ActionResult> SubscribeBookAsync(string userId, int bookId)
        {
            var resultBook = await _mediatr.Send(new SubscrubeBook() { UserId = userId, BookId = bookId });
            return View(resultBook);
        }
    }
}

Library/Views/Catalog/BooksList.cshtml
@model Library.ViewModels.CatalogViewModel;
@{
    ViewData["Title"] = "Каталог";
}
@if (Model.User == null)
{
    <p style="color:red">Авторизуйтесь, чтобы иметь возможность бронировать книги</p>
}
<div class="grid">
    <div class="booksFilters">
        <form method="get" asp-action="BooksList">
            <filters>
                <label>Название: </label>
                <input name="SearchString" style="width:200px" class="form-control" value="@Model.BooksFilterViewModel.SearchString" /><br />
                <label>Автор: </label>
                <select name="AuthorId" style="width:200px" class="form-control" asp-items="@Model.BooksFilterViewModel.Authors"></select><br />
                <label>Жанр: </label>
                <select name="GenreId" style="width:200px" class="form-control" asp-items="@Model.BooksFilterViewModel.Genres"></select><br />
                <label>Издатель: </label>
                <select name="PublisherId" style="width:200px" class="form-control" asp-items="@Model.BooksFilterViewModel.Publishers"></select><br />
                <input type="submit" value="Фильтр" class="btn btn-outline-dark" />
            </filters>
        </form>
    </div>
    <div class="books">
        @foreach (var book in Model.Books)
        {
            <div>
                <article>
                    <img src="~/Images/@book.Picture" width="200" height="250" alt="Изображение книги" />
                    <text>
                        Название: @book.NameBook<br />
                        Автор: @book.AuthorName<br />
                        Жанр: @book.GenreName <br />
                        Издательство: @book.PublisherName
                    </text>
                    <br />
                    @if (Model.User != null && Model.User.EmailConfirmed)
                    {
                        if (book.IsAvailable)
                        {
                            <a class="btn btn-outline-primary" href="/Catalog/ReserveBook?BookId=@book.Id&UserId=@Model.User.Id">Бронировать</a>
                        }
                        else
                        {
                            <p>Бронирование не доступно</p>
                            if (Model.User.Subscriptions.FirstOrDefault(s => s.BookId == book.Id) == null || Model.User.Subscriptions == null)
                            {
                                <a class="btn btn-outline-primary" href="/Catalog/SubscribeBook?BookId=@book.Id&UserId=@Model.User.Id">Подписаться на обновления</a>
                            }
                        }
                    }


                    else if (Model.User != null && !Model.User.EmailConfirmed)
                    {
                        <p>Перейдите по ссылке в письме вышленном на Вашу почту для завершения регистрации</p>
                    }
                    <div class="dropdown-divider"></div>
                </article>
            </div>
        }
    </div>

    <footer class="">
        <div>
            @if (Model.PageViewModel.HasPreviousPage)
            {
                <a asp-action="BooksList"
                   asp-route-page="@(Model.PageViewModel.PageNumber-1)"
                   asp-route-SearchString="@(Model.BooksFilterViewModel.SearchString)"
                   asp-route-AuthorId="@(Model.BooksFilterViewModel.SelectedAuthor)"
                   asp-route-GenreId="@(Model.BooksFilterViewModel.SelectedGenre)"
                   asp-route-PublisherId="@(Model.BooksFilterViewModel.SelectedPublisher)"
                   class="btn btn-outline-dark">
                    <i class="dropdown-menu-lg-left"></i>
                    Назад
                </a>
            }
        </div>
        <div>
            @if (Model.PageViewModel.HasNextPage)
            {
                <a asp-action="BooksList"
                   asp-route-page="@(Model.PageViewModel.PageNumber+1)"
                   asp-route-SearchString="@(Model.BooksFilterViewModel.SearchString)"
                   asp-route-AuthorId="@(Model.BooksFilterViewModel.SelectedAuthor)"
                   asp-route-GenreId="@(Model.BooksFilterViewModel.SelectedGenre)"
                   asp-route-PublisherId="@(Model.BooksFilterViewModel.SelectedPublisher)"
                   class="btn btn-outline-dark">
                    <i class="dropdown-menu-lg-right"></i>
                    Вперед
                </a>
            }
        </div>
    </footer>
</div>

Library/Views/Catalog/ReserveBook.cshtml
@model Library.ViewModels.BookSelectViewModel
@{
    ViewData["Title"] = "";
}
<h2>Вы зарезервировали книгу "@Model.NameBook".</h2>
<p>Вы можете забрать зарезервированную книгу в библиотеке в течение трёх дней</p>
@Html.ActionLink("Вернуться к каталогу", "BooksList","Catalog")
@Html.ActionLink("Мои книги", "MyReservations", "Reservation")

Library/Views/Catalog/SubscribeBook.cshtml
@model Library.ViewModels.BookSelectViewModel
@{ 
    ViewData["Title"] = "Подписка на обновления";
}
<h2>Вы подписались на получение уведомлений по книге @Model.NameBook</h2>
@Html.ActionLink("Каталог","BooksList")